name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Amazon ECR
        uses: docker/login-action@v1
        with:
          registry: 783633885093.dkr.ecr.us-west-2.amazonaws.com
          username: ${{ secrets.ACCESS_KEY_ID }}
          password: ${{ secrets.SECRET_ACCESS_KEY }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/mentoring
          tag_with_ref: true
